// Copyright 2011 Semantic Expression, Inc. All rights reserved.
//
// This program and the accompanying materials are made available under the
// terms of the GNU General Public License, either version 3 or (at your option)
// any later version. The terms of this license may be found at
// http://www.gnu.org/copyleft/gpl.html
//
// This program is made available on an "as is" basis, without warranties or
// conditions of any kind, either express or implied.
//
// Please contact us for other licensing options.
//
// Contributors:
//
// Anthony F. Stuart - Initial implementation
//
//
//

package com.semanticexpression.connector.server.repository;

public class AuthorityTableCreator extends DatabaseTableCreator
{
  public AuthorityTableCreator()
  {
    super("authority");
    appendPrefix();
    append("id integer generated by default as identity (start with 1, increment by 1) not null,");
    append("workflow_id bigint not null references entity(id) on delete cascade,");
    append("content_id bigint not null references entity(id) on delete cascade,");
    append("granted_to_id bigint not null references entity(id) on delete cascade,");
    append("granted_to_type smallint not null,");
    append("access_type smallint not null,");
    append("primary key(id)");
    appendSuffix();
  }
}
