// Copyright 2011 Semantic Expression, Inc. All rights reserved.
//
// This program and the accompanying materials are made available under the
// terms of the GNU General Public License, either version 3 or (at your option)
// any later version. The terms of this license may be found at
// http://www.gnu.org/copyleft/gpl.html
//
// This program is made available on an "as is" basis, without warranties or
// conditions of any kind, either express or implied.
//
// Please contact us for other licensing options.
//
// Contributors:
//
// Anthony F. Stuart - Initial implementation
//
//
//

package com.semanticexpression.connector.server.repository;


public class EntityTableCreator extends DatabaseTableCreator
{
  public EntityTableCreator()
  {
    super("entity");
    appendPrefix();
    append("id bigint generated by default as identity (start with 1, increment by 1) not null,");
    append("type smallint not null,");
    append("name varchar(" + Repository.MAX_NAME_LENGTH + "),");
    append("parent_entity_id bigint references entity(id) on delete cascade,");
    append("created_by bigint references entity(id) on delete cascade,");
    append("created_at bigint,");
    append("published_at bigint,");
    append("primary key(id),");
    append("unique(type, name)");
    appendSuffix();
  }
}
